# Generated by Django 4.0.2 on 2022-02-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('auther_address', models.CharField(max_length=200)),
                ('auther_dateofbr', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='bookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('public_date', models.DateField()),
                ('book_price', models.CharField(max_length=10)),
                ('Book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.book_category')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.authers')),
            ],
        ),
    ]
