# Generated by Django 4.0.2 on 2022-02-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='Book_category',
            new_name='Book_categorys',
        ),
    ]
