# Generated by Django 4.0.2 on 2022-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_booklist_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='book_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
