# Generated by Django 4.0.2 on 2022-02-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_booklist_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
                ('image_slider', models.ImageField(upload_to='slider')),
            ],
        ),
        migrations.AlterField(
            model_name='booklist',
            name='book_image',
            field=models.ImageField(upload_to='book_image'),
        ),
    ]
