# Generated by Django 4.0.2 on 2022-02-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_home_slider_alter_booklist_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='authers',
            name='author_photo',
            field=models.ImageField(default=1, upload_to='author'),
            preserve_default=False,
        ),
    ]
