# Generated by Django 4.0.2 on 2022-02-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_authers_author_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_product_id', models.IntegerField()),
            ],
        ),
    ]
